### ISSUE TITLE
Modules are sorted lexicographically, not numerically

### ISSUE THREAD

**Issue by KaneTW** [mbuesch/pyprofibus#14]
Modules are sorted lexicographically, not numerically: 
https://github.com/mbuesch/pyprofibus/blob/0abfaff88442e9d0af3ee83901a7e5fb933d50eb/pyprofibus/conf.py#L211

This is counterintuitive, as 

a) the regex forces a \d 
b) the examples have a number

As a result, module_2 comes after module_10, breaking the configuration.

**Comment by mbuesch** [comment]
Good catch. Thanks.
It was supposed to sort numerically, but I forgot the conversion from str to int.
I will fix that in the next version.
