### ISSUE TITLE
"input byte, "output byte" confusion

### ISSUE THREAD

**Issue by Sigma1912** [mbuesch/pyprofibus#21]
We have quickly touched on this in my earlier issues. I've had another look at this:

```
; The number of output bytes this slave transmits to the
; master in Data_Exchange.
; This usually depends on the modules plugged into the slave.
output_size=2

; The number of input bytes this slave expects to receive
; in Data_Exchange.
; This usually depends on the modules plugged into the slave.
input_size=0
```

Still seems wrong to me. My Festo Valve block expects 2 bytes FROM the master and transmits 0 bytes TO the master.  So if the above is defined as viewed from the slave then "output_size" should be "0" and "input_size" should be "2". If it's defined as viewed from the master then the comments should be swapped.

**Comment by mbuesch** [comment]
These two options reside in the `[SLAVE_x]` section(s) of the configuration.
All options in these sections configure the slave.
Therefore the terms `output` and `input` are to be interpreted from the slave's perspective. Just like the comment suggests.
That means your values are swapped.
