### ISSUE TITLE
pyprofibus hardware documentation

### ISSUE THREAD

**Issue by omidfathi** [mbuesch/pyprofibus#22]
hello

pyprofibus hardware documentation which is linked, doesn't work.

thanks for your work

**Comment by mbuesch** [comment]
Thanks for your message.
The documentation links work correctly in the pyprofibus release packages only.

**Comment by mbuesch** [comment]
Duplicate of #6

**Comment by mbuesch** [comment]
The master branch commit baea2df6e3ead2f5f1fa16d15867c4649cf50d1a changes pyprofibus documentation links to work correctly in checkout and release archive.
Can you please check if this works for you?
Thanks!
