### ISSUE TITLE
TxDen pin Question

### ISSUE THREAD

**Issue by TadyTheFish** [mbuesch/pyprofibus#23]
Hello
I can't find any description where to connect the TxDen pin if using a raspberry pi?

**Comment by mbuesch** [comment]
The TxDen pin is for switching the transceiver into transmit mode.
It can be used on devices that support fast HW based RTS signalling. As far as I know (please correct me if I'm wrong), the Raspi can't do that.

I use the timing circuitry for TxDen.
This circuitry could also be replaced by a simpler capacitor based solution. Especially if you don't want to support a wide range of baud rates.

**Comment by TadyTheFish** [comment]
I eill try some custom overlays for the Pi that should enable the RTS pin.

A aide question... Does anyone have a working example with the wago 750-343?
Thank you

**Comment by TadyTheFish** [comment]
Thank you!
