### ISSUE TITLE
Working over Ethernet

### ISSUE THREAD

**Issue by yoelk** [mbuesch/pyprofibus#3]
Hello,
I found your library and it looks great!
After looking around, I see that only serial interfaces are supported (or did I miss something?).

Do you think it would be a big issue to support Ethernet as well?
This would be the preferred mode of communication for my PLC project.

Thanks,
Joel

**Comment by mbuesch** [comment]
If by Ethernet you mean Profinet then the answer is: That won't ever happen. Profibus and Profinet are two completely different things. They basically only share the name.

**Comment by yoelk** [comment]
Thanks a lot, sorry for silly question :)
