### ISSUE TITLE
Getting telegram error

### ISSUE THREAD

**Issue by PEV93** [mbuesch/pyprofibus#8]
Hello
I am working with profibus on RS485 with a PLC S7-315 running with a speed of 9600bps.
I tried to get data on my PC by using RS485 to USB adaptaters and pyprofibus. 
I can't get any profibus valid Profibus data." 
Is there a compatibility list of adapters which work with pryprofibus ?I also try to get data with a tiny FPGA but I can't figure how to connect the pyprofibus to the tiny FPGA board. 
Is there some document to help me ?

**Comment by mbuesch** [comment]
Thanks for your report.

The use of USB adapters is problematic with Profibus. Such devices usually are unable to meet the strict realtime timing requirements of Profibus. Thus using any kind of USB adapter is unsupported. It is suggested to use a native serial interface, such as a real serial card put into the PCI(e) slot of a PC or such as a real serial port on an embedded machine (e.g. Raspberry Pi).
Alternatively a Tinyfpga board can be used. The advantage being that higher speeds are possible. The disadvantage is that its more complex and even more experimental than the rest of pyprofibus. 

In addition to that, pyprofibus can currently only operate in DP-Master mode or passive sniffer (profisniff). DP-Slave mode currently isn't supported.

All available documentation is included in the pyprofibus git repository or on the pyprofibus website.

**Comment by mbuesch** [comment]
Was the previous answer helpful?
If there's anything unclear, please don't hesitate to ask.

**Comment by PEV93** [comment]
Yes of course. Thanks for your help.
